### ISSUE TITLE
GIRAFFE with CAMPARI Camera Generator

### ISSUE THREAD

**Issue by sherwinbahmani** [autonomousvision/campari#1]
Hi Michael,

thanks a lot for the release of your code. I am using your GIRAFFE implementation and having a hard time there hand-tuning the camera parameters for good results using an own dataset. That's why I thought that it would make sense to use the camera generator from CAMPARI to learn the parameters during GIRAFFE training. Do you think it makes sense to simply plug-in this camera generator into your GIRAFFE framework to learn everything end-to-end or are there any problems I am not aware of doing this approach? 

Maybe you can also share a little bit more insight how you generally hand-tune the camera paramters for GIRAFFE / CAMPARI, as I can not generalize your models to new datasets so easily.

Best,
Sherwin

**Comment by RajabMuhammad** [comment]
Hi Micheal,
Thank you for the good work. 
Can you please share a link to the (bash scripts/download_dataset.sh)
